# Generated by Django 3.2.23 on 2024-01-26 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0007_alter_recipe_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("favorites", "0002_auto_20240125_1817"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_option",
                to="recipes.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="option_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
