# Generated by Django 5.0.1 on 2024-01-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="calories",
        ),
        migrations.AddField(
            model_name="recipe",
            name="level",
            field=models.CharField(
                choices=[
                    ("easy", "Easy"),
                    ("moderate", "Moderate"),
                    ("fancy", "Fancy"),
                ],
                default="easy",
                max_length=50,
            ),
        ),
    ]
