# Generated by Django 5.0.1 on 2024-01-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_remove_recipe_calories_recipe_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="method",
            field=models.CharField(
                choices=[
                    ("stovetop", "Stovetop"),
                    ("oven", "Oven"),
                    ("microwave", "Microwave"),
                ],
                default="stovetop",
                max_length=50,
            ),
        ),
    ]
