# Generated by Django 3.2.23 on 2024-01-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_remove_recipe_cuisine_types_remove_recipe_meal_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="tag1",
            field=models.CharField(
                choices=[
                    ("keto", "Keto"),
                    ("vegan", "Vegan"),
                    ("gluten-free", "Gluten-free"),
                    ("parve", "Parve"),
                    ("nut-free", "Nut-free"),
                    ("dairy-free", "Dairy-free"),
                ],
                default="keto",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="tag2",
            field=models.CharField(
                choices=[
                    ("keto", "Keto"),
                    ("vegan", "Vegan"),
                    ("gluten-free", "Gluten-free"),
                    ("parve", "Parve"),
                    ("nut-free", "Nut-free"),
                    ("dairy-free", "Dairy-free"),
                    ("--", "--"),
                ],
                default="keto",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="tag3",
            field=models.CharField(
                choices=[
                    ("keto", "Keto"),
                    ("vegan", "Vegan"),
                    ("gluten-free", "Gluten-free"),
                    ("parve", "Parve"),
                    ("nut-free", "Nut-free"),
                    ("dairy-free", "Dairy-free"),
                    ("--", "--"),
                ],
                default="keto",
                max_length=50,
            ),
        ),
    ]
